/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiPublicHooksEnviarCobrancasRouteImport } from './routes/api/public/hooks/enviar-cobrancas'
import { Route as ApiPublicWebhookEvolutionRouteImport } from './routes/api/public/webhook/evolution'

const ApiPublicHooksEnviarCobrancasRoute =
  ApiPublicHooksEnviarCobrancasRouteImport.update({
    id: '/api/public/hooks/enviar-cobrancas',
    path: '/api/public/hooks/enviar-cobrancas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookEvolutionRoute =
  ApiPublicWebhookEvolutionRouteImport.update({
    id: '/api/public/webhook/evolution',
    path: '/api/public/webhook/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/api/public/hooks/enviar-cobrancas': typeof ApiPublicHooksEnviarCobrancasRoute
  '/api/public/webhook/evolution': typeof ApiPublicWebhookEvolutionRoute
}
export interface FileRoutesByTo {
  '/api/public/hooks/enviar-cobrancas': typeof ApiPublicHooksEnviarCobrancasRoute
  '/api/public/webhook/evolution': typeof ApiPublicWebhookEvolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/public/hooks/enviar-cobrancas': typeof ApiPublicHooksEnviarCobrancasRoute
  '/api/public/webhook/evolution': typeof ApiPublicWebhookEvolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/api/public/hooks/enviar-cobrancas' | '/api/public/webhook/evolution'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/public/hooks/enviar-cobrancas' | '/api/public/webhook/evolution'
  id:
    | '__root__'
    | '/api/public/hooks/enviar-cobrancas'
    | '/api/public/webhook/evolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiPublicHooksEnviarCobrancasRoute: typeof ApiPublicHooksEnviarCobrancasRoute
  ApiPublicWebhookEvolutionRoute: typeof ApiPublicWebhookEvolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/public/hooks/enviar-cobrancas': {
      id: '/api/public/hooks/enviar-cobrancas'
      path: '/api/public/hooks/enviar-cobrancas'
      fullPath: '/api/public/hooks/enviar-cobrancas'
      preLoaderRoute: typeof ApiPublicHooksEnviarCobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/evolution': {
      id: '/api/public/webhook/evolution'
      path: '/api/public/webhook/evolution'
      fullPath: '/api/public/webhook/evolution'
      preLoaderRoute: typeof ApiPublicWebhookEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiPublicHooksEnviarCobrancasRoute: ApiPublicHooksEnviarCobrancasRoute,
  ApiPublicWebhookEvolutionRoute: ApiPublicWebhookEvolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
