/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConfiguracaoRouteImport } from './routes/_authenticated/configuracao'
import { Route as ApiPublicHooksEnviarCobrancasRouteImport } from './routes/api/public/hooks/enviar-cobrancas'
import { Route as ApiPublicWebhookEvolutionRouteImport } from './routes/api/public/webhook/evolution'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracaoRoute =
  AuthenticatedConfiguracaoRouteImport.update({
    id: '/configuracao',
    path: '/configuracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksEnviarCobrancasRoute =
  ApiPublicHooksEnviarCobrancasRouteImport.update({
    id: '/api/public/hooks/enviar-cobrancas',
    path: '/api/public/hooks/enviar-cobrancas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhookEvolutionRoute =
  ApiPublicWebhookEvolutionRouteImport.update({
    id: '/api/public/webhook/evolution',
    path: '/api/public/webhook/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/configuracao': typeof AuthenticatedConfiguracaoRoute
  '/api/public/hooks/enviar-cobrancas': typeof ApiPublicHooksEnviarCobrancasRoute
  '/api/public/webhook/evolution': typeof ApiPublicWebhookEvolutionRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/configuracao': typeof AuthenticatedConfiguracaoRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/enviar-cobrancas': typeof ApiPublicHooksEnviarCobrancasRoute
  '/api/public/webhook/evolution': typeof ApiPublicWebhookEvolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracao': typeof AuthenticatedConfiguracaoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/enviar-cobrancas': typeof ApiPublicHooksEnviarCobrancasRoute
  '/api/public/webhook/evolution': typeof ApiPublicWebhookEvolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracao'
    | '/api/public/hooks/enviar-cobrancas'
    | '/api/public/webhook/evolution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/configuracao'
    | '/'
    | '/api/public/hooks/enviar-cobrancas'
    | '/api/public/webhook/evolution'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracao'
    | '/_authenticated/'
    | '/api/public/hooks/enviar-cobrancas'
    | '/api/public/webhook/evolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksEnviarCobrancasRoute: typeof ApiPublicHooksEnviarCobrancasRoute
  ApiPublicWebhookEvolutionRoute: typeof ApiPublicWebhookEvolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracao': {
      id: '/_authenticated/configuracao'
      path: '/configuracao'
      fullPath: '/configuracao'
      preLoaderRoute: typeof AuthenticatedConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/enviar-cobrancas': {
      id: '/api/public/hooks/enviar-cobrancas'
      path: '/api/public/hooks/enviar-cobrancas'
      fullPath: '/api/public/hooks/enviar-cobrancas'
      preLoaderRoute: typeof ApiPublicHooksEnviarCobrancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/evolution': {
      id: '/api/public/webhook/evolution'
      path: '/api/public/webhook/evolution'
      fullPath: '/api/public/webhook/evolution'
      preLoaderRoute: typeof ApiPublicWebhookEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracaoRoute: typeof AuthenticatedConfiguracaoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracaoRoute: AuthenticatedConfiguracaoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksEnviarCobrancasRoute: ApiPublicHooksEnviarCobrancasRoute,
  ApiPublicWebhookEvolutionRoute: ApiPublicWebhookEvolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
